=== pierremancini/osiris-schema/JSON schema/master-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Schema général décrivant OSIRIS",
  "title": "Parent schema OSIRIS",
  "type": "object",
  "required": ["Patient"],
  "properties": {

    "AdverseEvent": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-AdverseEvent.json"
    },

    "Analysis": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Analysis.json"
    },

    "Annotation": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Annotation.json"
    },

    "BiologicalSample": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-BiologicalSample.json"
    },

    "Biomarker": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Biomarker.json"
    },

    "CancerHistory": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-CancerHistory.json"
    },

    "Consent": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Consent.json"
    },

    "CopyNumber": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-CopyNumber.json"
    },

    "Drug": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Drug.json"
    },

    "Expression": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Expression.json"
    },

    "FamillyCancerHistoy": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-FamillyCancerHistoy.json"
    },

    "Fusion": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Fusion.json"
    },

    "Patient": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Patient.json"
    },

    "RelatedPathology": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-RelatedPathology.json"
    },

    "ResponseEvalutaion": { 
      "$ref": "file://home/pmancini/Code/osiris-schema/JSON schema/schema-ResponseEvalutaion.json"
    },

    "TNM": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-TNM.json"
    },

    "Treatment": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Treatment.json"
    },

    "TumorPathologyEvent": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-TumorPathologyEvent.json"
    },

    "Variant": { 
      "$ref": "file:///home/pmancini/Code/osiris-schema/JSON schema/schema-Variant.json"
    }
  }
}

=== pierremancini/osiris-schema/JSON schema/test/master-test.json
{
  "AdverseEvent": [{
    "Patient_Id": "L304",
    "Instance_Id": 1,
    "Treatment_Ref": 2,
    "TumorPahtologyEvent_Ref": 1,
    "AdverseEvent_Code": "Mal Ã  la tete",
    "AdverseEvent_Date": "2007-06-13",
    "AdverseEvent_EndDate": "2007-07-10",
    "AdverseEvent_Grade": ""
  }],

  "Analysis": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "TumorPathologyEvent_Ref": 1,
      "BiologicalSample_Ref": "ech primary",
      "Analysis_Code": "ATX90U",
      "Analysis_Type": "Genomique",
      "Analysis_Date": "2018-02-07",
      "Technology_TechnicalProtocol": "OSIRIS:O6-4",
      "Technology_PlatformName": "OSIRIS:O7-66",
      "Technology_PlatformAccession": "",
      "Technology_DateOfExperiment": "2017-09-20",
      "Panel_Name": "OSIRIS:O10-4",
      "AnalysisProcess_AnalyticPipelineCode": "v351",
      "OmicAnalysis_AlgorithmicCellularity": 50,
      "OmicAnalysis_AlgorithmicPloidy": "OSIRIS:O13-2",
      "OmicAnalysis_NumberOfBreakPoints": ""
    },
    {
      "Patient_Id": "L304",
      "Instance_Id": 2,
      "TumorPathologyEvent_Ref": 2,
      "BiologicalSample_Ref": "ech 2",
      "Analysis_Code": "fgh587",
      "Analysis_Type": "NGS",
      "Analysis_Date": "2018-02-07",
      "Technology_TechnicalProtocol": "OSIRIS:O6-12",
      "Technology_PlatformName": "OSIRIS:O7-46",
      "Technology_PlatformAccession": "",
      "Technology_DateOfExperiment": "2017-09-19",
      "Panel_Name": "OSIRIS:O10-0",
      "AnalysisProcess_AnalyticPipelineCode": "RNAseq pipeline v3.2",
      "OmicAnalysis_AlgorithmicCellularity": 50,
      "OmicAnalysis_AlgorithmicPloidy": "OSIRIS:O13-2",
      "OmicAnalysis_NumberOfBreakPoints": ""
    },
    {
      "Patient_Id": "L304",
      "Instance_Id": 3,
      "TumorPathologyEvent_Ref": 2,
      "BiologicalSample_Ref": "ech 2",
      "Analysis_Code": "rt52485",
      "Analysis_Type": "Genomique",
      "Analysis_Date": "2018-02-09",
      "Technology_TechnicalProtocol": "OSIRIS:O6-3",
      "Technology_PlatformName": "OSIRIS:O7-25",
      "Technology_PlatformAccession": "",
      "Technology_DateOfExperiment": "2018-02-09",
      "Panel_Name": "OSIRIS:O10-0",
      "AnalysisProcess_AnalyticPipelineCode": "sbd54dsf57s",
      "OmicAnalysis_AlgorithmicCellularity": "",
      "OmicAnalysis_AlgorithmicPloidy": "",
      "OmicAnalysis_NumberOfBreakPoints": 320
    }
  ],

  "Annotation": [{
    "Patient_Id": "L304",
    "Instance_Id": 1,
    "Alteration_Ref": 1,
    "AlterationOnSample_AlterationType": "OSIRIS:O15-4",
    "Annotation_ReferenceType": "OSIRIS:O90-1",
    "Annotation_ReferenceDatabase": "COSMIC",
    "Annotation_ReferenceValue": "COSM760",
    "Annotation_Symbol": "PI3K",
    "Annotation_PfamDomain": "PI3K_rbd; PI3-kinase family, ras-binding domain",
    "Annotation_PfamId": "pfam00794",
    "Annotation_MutationPredictionAlgorithm": "SIFT",
    "Annotation_MutationPredictionValue": "Deleterious",
    "Annotation_MutationPredictionScore": 0.35,
    "Annotation_DNARegionName": "exon 2",
    "Annotation_DNASequenceVariation": "c.1624G>A",
    "Annotation_AminoAcidChange": "p.E542K",
    "Annotation_GenomicSequenceVariation": "",
    "Annotation_RNASequenceVariation": "",
    "Annotation_AminoAcidChangeType": "LA6698-0",
    "FusionPrimeEnd": "",
    "Strand": ""
  }],

  "BiologicalSample": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "TumorPathologyEvent_Ref": 1,
      "Consent_Ref": 1,
      "BiologicalSample_SampleExternalAccession": "ech primary",
      "BiologicalSample_ParentSampleExternalAccession": "",
      "BiologicalSample_CollectDate": "2005-12-27",
      "BiologicalSample_TopographyCode": "C34",
      "BiologicalSample_Nature": "C4039816",
      "BiologicalSample_Origin": "OSIRIS:O59-2",
      "BiologicalSample_StorageTemperature": "MIABIS:Tissue Frozen",
      "BiologicalSample_TumorCellularity": 30
    },
    {
      "Patient_Id": "L304",
      "Instance_Id": 2,
      "TumorPathologyEvent_Ref": 2,
      "Consent_Ref": 1,
      "BiologicalSample_SampleExternalAccession": "ech 2",
      "BiologicalSample_ParentSampleExternalAccession": "ech primary",
      "BiologicalSample_CollectDate": "2011-02-08",
      "BiologicalSample_TopographyCode": "C30",
      "BiologicalSample_Nature": "C1519524",
      "BiologicalSample_Origin": "OSIRIS:O59-2",
      "BiologicalSample_StorageTemperature": "FFPE",
      "BiologicalSample_TumorCellularity": 60
    }
  ],

  "Biomarker": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Analysis_Ref": 1,
      "Biomarker_Code": "cg6548",
      "Biomarker_Value": "++",
      "Biomarker_Unit": ""
    }
  ],

  "CancerHistory": { 

  },

  "Consent": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Consent_Date": "2000-11-16",
      "Consent_GeneticAnalysisAuthorization": 0
    }
  ],

  "CopyNumber": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Analysis_Ref": 3,
      "AlterationOnSample_AlterationType": "OSIRIS:O15-4",
      "AlterationOnSample_Pathogenicity": "",
      "AlterationOnSample_Actionability": "",
      "AlterationOnSample_ProposedForOrientation": "",
      "Alteration_Chromosome": "LA21263-1",
      "Alteration_GenomicStart": 87751512,
      "Alteration_GenomicStop": 88104391,
      "Alteration_GenomeBuild": "hg19",
      "Alteration_Cytoband": "10q23.31",
      "CNV_SegmentIntensity": 33,
      "CNV_SegmentGenomicStatus": "OSIRIS:O49-2",
      "CNV_CopyNumber": 3,
      "CNV_LOH": 0,
      "Validation_Type": "OSIRIS:O16-2",
      "Validation_Method": "Visual check",
      "Validation_Status": "OSIRIS:O18-2"
    }
  ],

  "Drug": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Treatment_Ref": 2,
      "Drug_Code": "c3564",
      "Drug_Name": "cis-platine"
    },
    {
      "Patient_Id": "L304",
      "Instance_Id": 2,
      "Treatment_Ref": 2,
      "Drug_Code": "f456",
      "Drug_Name": "Imatinib"
    }
  ],

  "Expression": [
    {
      "Patient_Id": "L304",
      "Instance_Id": "",
      "Analysis_Ref": "",
      "AlterationOnSample_AlterationType": "",
      "AlterationOnSample_Pathogenicity": "",
      "AlterationOnSample_Actionability": "",
      "AlterationOnSample_ProposedForOrientation": "",
      "GenomeEntity_Type": "",
      "GenomeEntity_Database": "",
      "GenomeEntity_Id": "",
      "GenomeEntity_Symbol": "",
      "GeneExpression_DataType": "",
      "GeneExpression_Value": "",
      "ValidationType": "",
      "Validation_Method": "",
      "Validation_Status": ""
    }
  ],

  "FamillyCancerHistoy": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "FamilyCancerHistory_TopographyCode": "C00.5",
      "FamilyCancerHistory_Parentage": "C0037047"
    }
  ],

  "Fusion": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Analysis_Ref": 2,
      "AlterationOnSample_AlterationType": "OSIRIS:O15-3",
      "AlterationOnSample_Pathogenicity": "",
      "AlterationOnSample_Actionability": "",
      "AlterationOnSample_ProposedForOrientation": "",
      "Fusion_Type": "LOINC:LA26331-1",
      "Fusion_Point5prime": "",
      "Fusion_Point3prime": "",
      "Fusion_NbSpanningPair": 33,
      "Fusion_NbSplitReads": 5,
      "Fusion_InFrame": 1,
      "Validation_Type": "OSIRIS:O16-3",
      "Validation_Method": "",
      "Validation_Status": "OSIRIS:O18-2"
    }
  ],

  "Patient": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Patient_Gender": "M",
      "Patient_Ethnicity": "2043-8",
      "Patient_BirthDate": "1967-11-08",
      "Patient_DeathDate": "2017-11-29",
      "Patient_ProviderCenterId": "IB",
      "Patient_OriginCenterId": "IB",
      "Patient_CauseOfDeath": "UMLS:C0027651",
      "Patient_LastNewsDate": "2017-11-29",
      "Patient_LastNewsStatus": "UMLS:C1546956"
    },
    {
      "Patient_Id": "L036",
      "Instance_Id": 2,
      "Patient_Gender": "",
      "Patient_Ethnicity": "",
      "Patient_BirthDate": "",
      "Patient_DeathDate": "",
      "Patient_ProviderCenterId": "",
      "Patient_OriginCenterId": "",
      "Patient_CauseOfDeath": "",
      "Patient_LastNewsDate": "",
      "Patient_LastNewsStatus": ""
    }
  ],

  "RelatedPathology": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "RelatedPathology_PathologyCode": "R60.9",
      "RelatedPathology_DiagnosisDate": "2002-11-14",
      "RelatedPathology_PathologyEndDate": "2003-11-19"
    }
  ],

  "ResponseEvalutaion": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "Treatment_Ref": 1,
      "Date": "",
      "Status": ""
    }
  ],

  "TNM": [
    {
      "Patient_Id": "L304",
      "Instance_Id": 1,
      "TumorPathologyEvent_ParentRef": "",
      "TumorPathologyEvent_Type": "UMLS:C0677930",
      "TumorPathologyEvent_StartDate": "2005-11-17",
      "TumorPathologyEvent_PerformanceStatus": 1,
      "TumorPathologyEvent_G8": 6,
      "TumorPathologyEvent_T": "T0",
      "TumorPathologyEvent_N": "N1mi",
      "TumorPathologyEvent_M": "M1",
      "TumorPathologyEvent_TNMVersion": "",
      "TumorPathologyEvent_TNMType": "c",
      "TumorPathologyEvent_HistologicalGradeType": "",
      "TumorPathologyEvent_HistologicalGradeValue": "",
      "TumorPathologyEvent_StadeType": "",
      "TumorPathologyEvent_StadeValue": "",
      "TumorPathologyEvent_DiagnosisDate": "2005-11-17",
      "TumorPathologyEvent_TopographyCode": "C00.8",
      "TumorPathologyEvent_MorphologyCode": "8002/3",
      "TumorPathologyEvent_Laterality": "UMLS:C0238767"
    },
    {
      "Patient_Id": "L304",
      "Instance_Id": 2,
      "TumorPathologyEvent_ParentRef": 1,
      "TumorPathologyEvent_Type": "UMLS:C0521158",
      "TumorPathologyEvent_StartDate": "2010-11-18",
      "TumorPathologyEvent_PerformanceStatus": 6,
      "TumorPathologyEvent_G8": 6,
      "TumorPathologyEvent_T": "T1",
      "TumorPathologyEvent_N": "N2",
      "TumorPathologyEvent_M": "M1",
      "TumorPathologyEvent_TNMVersion": "",
      "TumorPathologyEvent_TNMType": "p",
